load("@pypi//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "blink_firmata",
    srcs = ["blink_firmata.py"],
    visibility = ["//visibility:public"],
    deps = [requirement("pyfirmata2")],
)

py_binary(
    name = "i2c_firmata",
    srcs = ["i2c_firmata.py"],
    visibility = ["//visibility:public"],
    deps = [requirement("pyfirmata2")],
)

py_binary(
    name = "mpu6050",
    srcs = ["mpu6050.py"],
    visibility = ["//visibility:public"],
    deps = [requirement("smbus2")],
)
