# yaml-language-server: $schema=https://raw.githubusercontent.com/bazelbuild/bazel-central-registry/main/metadata.schema.json
###############################################################################
# Bazel now uses Bzlmod by default to manage external dependencies.
# Please consider migrating your external dependencies from WORKSPACE to MODULE.bazel.
#
# For more details, please check https://github.com/bazelbuild/bazel/issues/18958
###############################################################################
module(name = "arduino_firmata_kernel_driver")

bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "rules_python", version = "1.9.0")

# Hedron's Compile Commands Extractor for Bazel
# https://github.com/hedronvision/bazel-compile-commands-extractor
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    # commit = "abb61a688167623088f8768cc9264798df6a9d10",  # Bleeding edge commit
    commit = "7fe1eab26d2b8eeb5e1c6a2f38bddb001e3f9696",  # Commit which works in another project with Bazel v9.0.1
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
    # Replace the commit hash (above) with the latest (https://github.com/hedronvision/bazel-compile-commands-extractor/commits/main).
    # Even better, set up Renovate and let it do the work for you (see "Suggestion: Updates" in the README).
)

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.14",
)
use_repo(python, "python_versions")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")

# We need to modify the telemetrix wheel before we move forward
pip.whl_mods(
    hub_name = "pypi_mods",
    whl_name = "telemetrix",
)
use_repo(pip, "pypi_mods")

pip.parse(
    hub_name = "pypi",
    python_version = "3.14",
    requirements_by_platform = {
        # Default requirements file for needs to explicitly provide the platforms
        "//:requirements_lock.txt": "linux_*,osx_*",
        "//:requirements_windows.txt": "windows_x86_64",
    },

    # These modifications were created above and we
    # are providing pip.parse with the label of the mod
    # and the name of the wheel.
    whl_modifications = {
        "@pypi_mods//:telemetrix.json": "telemetrix",
    },
)

# You can add patches that will be applied on the whl contents.
#
# The patches have to be in the unified-diff format.
pip.override(
    file = "telemetrix-1.46-py3-none-any.whl",
    patch_strip = 1,
    patches = [
        "//patches:telemetrix_remove_archive.patch",
        "//patches:telemetrix_record.patch",
        "//patches:telemetrix_remove_runtime_error.patch",
        "//patches:telemetrix_record_remove_runtime_error.patch",
    ],
)
use_repo(pip, "pypi")

# # For firmata4j
# bazel_dep(name = "rules_java", version = "9.6.1")
# bazel_dep(name = "rules_jvm_external", version = "6.10")

# # We need this due to: https://github.com/bazel-contrib/rules_jvm_external/issues/1535
# single_version_override(
#     module_name = "rules_android",
#     version = "0.7.1",
# )

# maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
# maven.install(
#     artifacts = [
#         # Source: https://mvnrepository.com/artifact/com.github.kurbatov/firmata4j
#         "com.github.kurbatov:firmata4j:master-798ebcc123-1",
#     ],
#     known_contributing_modules = ["protobuf"],
#     lock_file = "//:maven_install.json",
#     repositories = [
#         "https://jitpack.io",
#     ],
# )
# use_repo(maven, "maven")

bazel_dep(name = "llvm", version = "0.6.0")

register_toolchains("@llvm//toolchain:all")

# https://github.com/fmeum/buildozer
BUILDOZER_VERSION = "8.2.1"

archive_override(
    module_name = "buildozer",
    integrity = "sha256-qguc6LLFdWL7OXk1Bm2fatLqzOEggu1Av5wAVNiJnec=",
    strip_prefix = "buildozer-%s" % BUILDOZER_VERSION,
    url = "https://github.com/fmeum/buildozer/releases/download/v{0}/buildozer-v{0}.tar.gz".format(BUILDOZER_VERSION),
)

# Taking inspiration from: https://github.com/robinlinden/hastur/blob/ce9041176637be99ef747f58bef83da0ca6f946f/MODULE.bazel
# HEAD as of 2026-01-05.
# https://github.com/erenon/bazel_clang_tidy
BAZEL_CLANG_TIDY_VERSION = "da986512bf1a46831d886fd090393b93b8967a5d"

bazel_dep(name = "bazel_clang_tidy", dev_dependency = True)  # MIT
archive_override(
    module_name = "bazel_clang_tidy",
    integrity = "sha256-WkayQxTZZiU6BVCPgCq0sDQoNrcPeGQa/vbM/UQRIS8=",
    strip_prefix = "bazel_clang_tidy-%s" % BAZEL_CLANG_TIDY_VERSION,
    url = "https://github.com/erenon/bazel_clang_tidy/archive/%s.tar.gz" % BAZEL_CLANG_TIDY_VERSION,
)
